# small docker-compose just to make building easier
services:
  app:
    build: .
    # user: root # debug
    # volumes: # debug
      # - .:/app
    # working_dir: /app # debug
    ports: 
      - "5000:5000"
    # environment: # debug
      # FLASK_APP: app
      # FLASK_ENV: development
      # FLASK_DEBUG: "1"


# HUSK AT FJERNE DEBUG TING INDEN AFLEVERING?
