version: "3.9"

services:

  frontend:
    build: ./frontend
    ports:
      - "5000:5000" 
    environment: 
      - AUTH_API_URL=http://auth:5000
      - COLLECTIVES_API_URL=http://collectives:5000
      - PROFILE_API_URL=http://profile:5000
      - PICTURES_API_URL=http://pictures:5000
    depends_on:
      - auth
      - collectives
      - profile
      - pictures

  auth:
    build: ./auth
    expose:
      - "5000"
    environment:
        # format: # postgresql://user:password@host:port/dbname
        # default user and dbname is postgres.
      - DATABASE_URL=postgresql://postgres:postgres@auth_db:5432/postgres
    depends_on:
      auth_db:
        condition: service_healthy                  # service's "healthiness" is assessed by the field "healthcheck"

  auth_db:
    image: postgres:17
    restart: always                                 # upon container termination, this container is restarted (untill removal). adviced on https://hub.docker.com/_/postgres
    environment:
      POSTGRES_PASSWORD: postgres                    # required env variable for postgres image (https://hub.docker.com/_/postgres)
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    healthcheck:                                    # determines if a service is "healthy" by running running the command in 'test'. https://docs.docker.com/reference/compose-file/services/#healthcheck
      test: ["CMD-SHELL", "pg_isready -U postgres"] # command to check if service is healthy
      retries: 5                                    # amount of retries before service is considered unhealthy
      interval: 5s                                  # first check is run 5s after service has started, then 5s after each previous check completes
      timeout: 5s                                   # if a test takes more than 5s to complete, the check is considered to have failed

  collectives:
    build: ./collectives
    expose:
      - "5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@collectives_db:5432/postgres
    depends_on:
      collectives_db:
        condition: service_healthy

  collectives_db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres          
    volumes:
      - collectives_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  profile:
    build: ./profile
    expose:
      - "5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@profile_db:5432/postgres
    depends_on:
      profile_db:
        condition: service_healthy

  profile_db:
    image: postgres:17
    restart: always 
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - profile_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pictures:
    build: ./pictures
    ports:
      - "5004:5000"                                 # Expose pictures service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@pictures_db:5432/postgres
    depends_on:
      pictures_db:
        condition: service_healthy

  pictures_db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pictures_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  auth_pgdata:
  collectives_pgdata:
  profile_pgdata:
  pictures_pgdata:

