version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000" 
    environment: 
      - AUTH_API_URL=http://auth:5000
      - COLLECTIVES_API_URL=http://collectives:5000
      - PROFILE_API_URL=http://profile:5000
      - PICTURES_API_URL=http://pictures:5000
    #TODO: FOR DEBUGGING
    volumes:                    # debug
      - ./frontend:/app         # debug
    command: flask run --debug  # debug
    depends_on:
      - auth
      - collectives
      - profile
      - pictures
  auth:
    build: ./auth
    expose:
      - "5000" # tilgå logic på 5001 porten
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@auth_db:5432/postgres
    #TODO: FOR DEBUGGING
    volumes:                    # debug
      - ./auth:/app             # debug
    command: flask run --debug  # debug
    depends_on:
      auth_db:
        condition: service_healthy
  
  collectives:
    build: ./collectives
    expose:
      - "5000"  # Expose collectives service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@collectives_db:5432/postgres
    #TODO: FOR DEBUGGING
    volumes:                    # debug
      - ./collectives/:/app     # debug
    command: flask run --debug  # debug
    depends_on:
      collectives_db:
        condition: service_healthy

  profile:
    build: ./profile
    expose:
      - "5000"  # Expose profile service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@profile_db:5432/postgres
    #TODO: FOR DEBUGGING
    volumes:                    # debug
      - ./profile/:/app     # debug
    command: flask run --debug  # debug
    depends_on:
      profile_db:
        condition: service_healthy

  pictures:
    build: ./pictures
    ports:
      - "5004:5000"  # Expose pictures service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@pictures_db:5432/postgres
    #TODO: FOR DEBUGGING
    volumes:                    # debug
      - ./pictures/:/app     # debug
    command: flask run --debug  # debug
    depends_on:
      pictures_db:
        condition: service_healthy


  auth_db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  collectives_db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - collectives_pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  profile_db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - profile_pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pictures_db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pictures_pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  auth_pgdata:
  collectives_pgdata:
  profile_pgdata:
  pictures_pgdata:

