version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000" 
    environment: 
      - AUTH_API_URL=http://auth:5000 # Container to container communication
      - COLLECTIVES_API_URL=http://collectives:5000
    #TODO: FOR DEBUGGING
    volumes:                    # debug
      - ./frontend:/app         # debug
    command: flask run --debug  # debug
    depends_on:
      - auth
      - collectives
  auth:
    build: ./auth
    ports:
      - "5001:5000" # tilgå logic på 5001 porten
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    #TODO: FOR DEBUGGING
    volumes:                    # debug
      - ./auth:/app             # debug
    command: flask run --debug  # debug
    depends_on:
      - db
  
  collectives:
    build: ./collectives
    ports:
      - "5002:5000"  # Expose collectives service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    #TODO: FOR DEBUGGING
    volumes:                    # debug
      - ./collectives/:/app     # debug
    command: flask run --debug  # debug
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local
